git:
  depth: 1

before_cache:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi

cache:
  directories:
    - $HOME/.cache/pyenv
    - /opt/pyenv/versions/$PYENV_VERSION
    - $HOME/pyenv/versions/$PYENV_VERSION
    - $HOME/Library/Caches/Homebrew
  pip: true

env:
  global:
    - PYTHON_BUILD_CACHE_PATH=$HOME/.cache/pyenv
    - HOMEBREW_NO_INSTALL_CLEANUP=1

jobs:
  fast_finish: true
  include:
    - &linux
      os: linux
      language: python
      env: PYENV_VERSION=2.6.9 TOXENV=py26
    - <<: *linux
      env: PYENV_VERSION=2.7.17 TOXENV=py27
    - <<: *linux
      env: PYENV_VERSION=2.7-dev TOXENV=py27
    - <<: *linux
      env: PYENV_VERSION=3.4.10 TOXENV=py34
    - <<: *linux
      env: PYENV_VERSION=3.5.8 TOXENV=py35
    - <<: *linux
      env: PYENV_VERSION=3.5-dev TOXENV=py35
    - <<: *linux
      env: PYENV_VERSION=3.6.9 TOXENV=py36
    - <<: *linux
      env: PYENV_VERSION=3.6-dev TOXENV=py36
    - <<: *linux
      env: PYENV_VERSION=3.7.5 TOXENV=py37
    - <<: *linux
      env: PYENV_VERSION=3.7-dev TOXENV=py37
    - <<: *linux
      env: PYENV_VERSION=3.8.0 TOXENV=py38
    - <<: *linux
      env: PYENV_VERSION=3.8-dev TOXENV=py38
    - <<: *linux
      env: PYENV_VERSION=3.9-dev TOXENV=py39
    - <<: *linux
      env: PYENV_VERSION=pypy2.7-7.2.0 TOXENV=pypy
    - <<: *linux
      env: PYENV_VERSION=pypy3.6-7.2.0 TOXENV=pypy3
    - &osx
      os: osx
      language: generic
      env: PYENV_VERSION=2.6.9 TOXENV=py26
    - <<: *osx
      env: PYENV_VERSION=2.7.17 TOXENV=py27
    - <<: *osx
      env: PYENV_VERSION=2.7-dev TOXENV=py27
    - <<: *osx
      env: PYENV_VERSION=3.4.10 TOXENV=py34
    - <<: *osx
      env: PYENV_VERSION=3.5.8 TOXENV=py35
    - <<: *osx
      env: PYENV_VERSION=3.5-dev TOXENV=py35
    - <<: *osx
      env: PYENV_VERSION=3.6.9 TOXENV=py36
    - <<: *osx
      env: PYENV_VERSION=3.6-dev TOXENV=py36
    - <<: *osx
      env: PYENV_VERSION=3.7.5 TOXENV=py37
    - <<: *osx
      env: PYENV_VERSION=3.7-dev TOXENV=py37
    - <<: *osx
      env: PYENV_VERSION=3.8.0 TOXENV=py38
    - <<: *osx
      env: PYENV_VERSION=3.8-dev TOXENV=py38
    - <<: *osx
      env: PYENV_VERSION=3.9-dev TOXENV=py39
    - <<: *osx
      env: PYENV_VERSION=pypy2.7-7.2.0 TOXENV=pypy
    - <<: *osx
      env: PYENV_VERSION=pypy3.6-7.2.0 TOXENV=pypy3
  allow_failures:
    - env: PYENV_VERSION=2.7-dev TOXENV=py27
    - env: PYENV_VERSION=3.5-dev TOXENV=py35
    - env: PYENV_VERSION=3.6-dev TOXENV=py36
    - env: PYENV_VERSION=3.7-dev TOXENV=py37
    - env: PYENV_VERSION=3.8-dev TOXENV=py38
    - env: PYENV_VERSION=3.9-dev TOXENV=py39

before_install:
  - mkdir -p ${HOME}/.cache/pyenv
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && (brew upgrade pyenv || true); fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git -C "$(pyenv root)" fetch && git -C "$(pyenv root)" checkout master && git -C "$(pyenv root)" pull; fi

install:
  - python -m pip install tox==3.14.0 codecov==2.0.15 tox-pyenv==1.1.0 virtualenv==15.2.0
  - pyenv install $(pyenv exec python --version >/dev/null 2>&1 && echo "--skip-existing" || echo "--force")  "${PYENV_VERSION}"

script:
  - python -m tox -vv -- --cov-report=xml

after_success:
  - python -m codecov --required

before_deploy:
  - python setup.py sdist bdist_wheel

deploy:
  - provider: pypi
    user: Ilya.Kulakov
    password:
      secure: "fDYi/HJvYyqUggKmN/Dc6YewUsBAzHWBdTYMpDfHETeOIvv2G268atnIwcoWav63fwPUpagwOlzQhRklqeLRmjEzr4M+wzFsAQVAnj6a7ChLPWPmgZlClFRpm6leWZjzGD+1FPnH/vvwTHlDi7j+1zgfh4WEellnw3hU+Lzjx+o="
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      branch: master
      python: 3.6
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "QHn7vzWo7rbgemP37qdNU4h+q7Xb2CQ7HxPFfa7yTsxFd8V4+sQLVrnaQtzYTM8dJWvRgi8PVHVGl2VGnQAiRM4Nd/NE/3HL9aHQIfWRtZ6XHfNVQ55bxJzLfZZy2M+32b8W268ELj3ty4C3Mo7TuOTv4svQoRDrLzGozJCpu+w="
    file_glob: true
    file: dist/*
    on:
      tags: true
      branch: master
      python: 3.6
