env:
  global:
  - PIP_URL="https://bootstrap.pypa.io/get-pip.py"
  - PIP="python -m pip"

matrix:
  fast_finish: true
  include:
  - os: osx
    language: generic
    env:
    - NAME="Python 2.6"
    - PIP_URL="https://bootstrap.pypa.io/2.6/get-pip.py"
    - PIP=pip
    before_install:
    - brew update
    - brew upgrade pyenv || brew install pyenv || true
    - pyenv install 2.6.9
    - pyenv local 2.6.9
    - eval "$(pyenv init -)"
    - pip install virtualenv
    - python2.6 -m virtualenv env
    - pyenv local --unset
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python 2.7"
    before_install:
    - brew update
    - brew upgrade python2 || true
    - python2.7 -m pip install virtualenv
    - python2.7 -m virtualenv env
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python pypy"
    before_install:
    - brew update
    - brew upgrade pypy || brew install pypy || true
    - pypy -m pip install virtualenv
    - pypy -m virtualenv env
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python 3.4"
    before_install:
    - brew update
    - brew upgrade pyenv || brew install pyenv || true
    - pyenv install 3.4.9
    - pyenv local 3.4.9
    - eval "$(pyenv init -)"
    - python3.4 -m venv env
    - pyenv local --unset
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python 3.5"
    before_install:
    - brew update
    - brew upgrade pyenv || brew install pyenv || true
    - pyenv install 3.5.6
    - pyenv local 3.5.6
    - eval "$(pyenv init -)"
    - python3.5 -m venv env
    - pyenv local --unset
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python 3.6"
    before_install:
    - brew update
    - brew upgrade pyenv || brew install pyenv || true
    - pyenv install 3.6.6
    - pyenv local 3.6.6
    - eval "$(pyenv init -)"
    - python3.6 -m venv env
    - pyenv local --unset
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python 3.7"
    before_install:
    - brew update
    - brew upgrade python || true
    - python3.7 -m venv env
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python HEAD"
    before_install:
    - brew update
    - brew unlink python
    - brew install python --HEAD
    - python3 -m venv env
    - source env/bin/activate
  - os: osx
    language: generic
    env: NAME="Python pypy3"
    before_install:
    - brew update
    - brew upgrade pypy3 || brew install pypy3 || true
    - pypy3 -m venv env
    - source env/bin/activate
  - os: linux
    env:
    - PIP_URL="https://bootstrap.pypa.io/2.6/get-pip.py"
    - PIP=pip
    language: python
    python: 2.6
  - os: linux
    language: python
    python: 2.7
  - os: linux
    language: python
    python: pypy
  - os: linux
    language: python
    python: 3.4
  - os: linux
    language: python
    python: 3.5
  - os: linux
    language: python
    python: 3.6
  - os: linux
    language: python
    python: 3.7
    dist: xenial
    sudo: true
  - os: linux
    language: python
    python: 3.6-dev
  - os: linux
    language: python
    python: 3.7-dev
  - os: linux
    language: python
    python: nightly
  - os: linux
    language: python
    python: pypy3
  allow_failures:
  - os: osx
    env: NAME="Python HEAD"
  - os: linux
    python: 3.6-dev
  - os: linux
    python: 3.7-dev
  - os: linux
    python: nightly

install:
- curl ${PIP_URL} | python
- ${PIP} install -r requirements.txt

script:
- make test

after_success:
- python -m codecov
- python setup.py sdist bdist_wheel

deploy:
- provider: pypi
  user: Ilya.Kulakov
  password:
    secure: "fDYi/HJvYyqUggKmN/Dc6YewUsBAzHWBdTYMpDfHETeOIvv2G268atnIwcoWav63fwPUpagwOlzQhRklqeLRmjEzr4M+wzFsAQVAnj6a7ChLPWPmgZlClFRpm6leWZjzGD+1FPnH/vvwTHlDi7j+1zgfh4WEellnw3hU+Lzjx+o="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
    python: 3.6
- provider: releases
  skip_cleanup: true
  api_key:
    secure: "QHn7vzWo7rbgemP37qdNU4h+q7Xb2CQ7HxPFfa7yTsxFd8V4+sQLVrnaQtzYTM8dJWvRgi8PVHVGl2VGnQAiRM4Nd/NE/3HL9aHQIfWRtZ6XHfNVQ55bxJzLfZZy2M+32b8W268ELj3ty4C3Mo7TuOTv4svQoRDrLzGozJCpu+w="
  file_glob: true
  file: dist/*
  on:
    tags: true
    branch: master
    python: 3.6
